/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TerminRouteImport } from './routes/termin'
import { Route as TherapienRouteImport } from './routes/therapien'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as AuthenticatedMeinBereichRouteImport } from './routes/_authenticated/mein-bereich'
import { Route as AuthenticatedPraxisRouteRouteImport } from './routes/_authenticated/praxis/route'
import { Route as AuthenticatedPraxisIndexRouteImport } from './routes/_authenticated/praxis/index'
import { Route as AuthenticatedPraxisAnfragenRouteImport } from './routes/_authenticated/praxis/anfragen'
import { Route as AuthenticatedPraxisEinstellungenRouteImport } from './routes/_authenticated/praxis/einstellungen'
import { Route as AuthenticatedPraxisHeuteRouteImport } from './routes/_authenticated/praxis/heute'
import { Route as AuthenticatedPraxisKalenderRouteImport } from './routes/_authenticated/praxis/kalender'
import { Route as AuthenticatedPraxisMahnungenRouteImport } from './routes/_authenticated/praxis/mahnungen'
import { Route as AuthenticatedPraxisNewsletterRouteImport } from './routes/_authenticated/praxis/newsletter'
import { Route as AuthenticatedPraxisRechnungenRouteImport } from './routes/_authenticated/praxis/rechnungen'
import { Route as AuthenticatedPraxisSucheRouteImport } from './routes/_authenticated/praxis/suche'
import { Route as AuthenticatedPraxisUebersichtRouteImport } from './routes/_authenticated/praxis/uebersicht'
import { Route as AuthenticatedPraxisZahlungenRouteImport } from './routes/_authenticated/praxis/zahlungen'
import { Route as AuthenticatedPraxisPatientenIndexRouteImport } from './routes/_authenticated/praxis/patienten.index'
import { Route as AuthenticatedPraxisPatientenPatientIdIndexRouteImport } from './routes/_authenticated/praxis/patienten.$patientId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminRoute = TerminRouteImport.update({
  id: '/termin',
  path: '/termin',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapienRoute = TherapienRouteImport.update({
  id: '/therapien',
  path: '/therapien',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const WiderrufRoute = WiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeinBereichRoute =
  AuthenticatedMeinBereichRouteImport.update({
    id: '/mein-bereich',
    path: '/mein-bereich',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPraxisRouteRoute =
  AuthenticatedPraxisRouteRouteImport.update({
    id: '/praxis',
    path: '/praxis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPraxisIndexRoute =
  AuthenticatedPraxisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisAnfragenRoute =
  AuthenticatedPraxisAnfragenRouteImport.update({
    id: '/anfragen',
    path: '/anfragen',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisEinstellungenRoute =
  AuthenticatedPraxisEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisHeuteRoute =
  AuthenticatedPraxisHeuteRouteImport.update({
    id: '/heute',
    path: '/heute',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisKalenderRoute =
  AuthenticatedPraxisKalenderRouteImport.update({
    id: '/kalender',
    path: '/kalender',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisMahnungenRoute =
  AuthenticatedPraxisMahnungenRouteImport.update({
    id: '/mahnungen',
    path: '/mahnungen',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisNewsletterRoute =
  AuthenticatedPraxisNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisRechnungenRoute =
  AuthenticatedPraxisRechnungenRouteImport.update({
    id: '/rechnungen',
    path: '/rechnungen',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisSucheRoute =
  AuthenticatedPraxisSucheRouteImport.update({
    id: '/suche',
    path: '/suche',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisUebersichtRoute =
  AuthenticatedPraxisUebersichtRouteImport.update({
    id: '/uebersicht',
    path: '/uebersicht',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisZahlungenRoute =
  AuthenticatedPraxisZahlungenRouteImport.update({
    id: '/zahlungen',
    path: '/zahlungen',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisPatientenIndexRoute =
  AuthenticatedPraxisPatientenIndexRouteImport.update({
    id: '/patienten/',
    path: '/patienten/',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)
const AuthenticatedPraxisPatientenPatientIdIndexRoute =
  AuthenticatedPraxisPatientenPatientIdIndexRouteImport.update({
    id: '/patienten/$patientId/',
    path: '/patienten/$patientId/',
    getParentRoute: () => AuthenticatedPraxisRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap': typeof SitemapRoute
  '/termin': typeof TerminRoute
  '/therapien': typeof TherapienRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/praxis': typeof AuthenticatedPraxisRouteRouteWithChildren
  '/mein-bereich': typeof AuthenticatedMeinBereichRoute
  '/praxis/anfragen': typeof AuthenticatedPraxisAnfragenRoute
  '/praxis/einstellungen': typeof AuthenticatedPraxisEinstellungenRoute
  '/praxis/heute': typeof AuthenticatedPraxisHeuteRoute
  '/praxis/kalender': typeof AuthenticatedPraxisKalenderRoute
  '/praxis/mahnungen': typeof AuthenticatedPraxisMahnungenRoute
  '/praxis/newsletter': typeof AuthenticatedPraxisNewsletterRoute
  '/praxis/rechnungen': typeof AuthenticatedPraxisRechnungenRoute
  '/praxis/suche': typeof AuthenticatedPraxisSucheRoute
  '/praxis/uebersicht': typeof AuthenticatedPraxisUebersichtRoute
  '/praxis/zahlungen': typeof AuthenticatedPraxisZahlungenRoute
  '/praxis/': typeof AuthenticatedPraxisIndexRoute
  '/praxis/patienten/': typeof AuthenticatedPraxisPatientenIndexRoute
  '/praxis/patienten/$patientId/': typeof AuthenticatedPraxisPatientenPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap': typeof SitemapRoute
  '/termin': typeof TerminRoute
  '/therapien': typeof TherapienRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/mein-bereich': typeof AuthenticatedMeinBereichRoute
  '/praxis/anfragen': typeof AuthenticatedPraxisAnfragenRoute
  '/praxis/einstellungen': typeof AuthenticatedPraxisEinstellungenRoute
  '/praxis/heute': typeof AuthenticatedPraxisHeuteRoute
  '/praxis/kalender': typeof AuthenticatedPraxisKalenderRoute
  '/praxis/mahnungen': typeof AuthenticatedPraxisMahnungenRoute
  '/praxis/newsletter': typeof AuthenticatedPraxisNewsletterRoute
  '/praxis/rechnungen': typeof AuthenticatedPraxisRechnungenRoute
  '/praxis/suche': typeof AuthenticatedPraxisSucheRoute
  '/praxis/uebersicht': typeof AuthenticatedPraxisUebersichtRoute
  '/praxis/zahlungen': typeof AuthenticatedPraxisZahlungenRoute
  '/praxis': typeof AuthenticatedPraxisIndexRoute
  '/praxis/patienten': typeof AuthenticatedPraxisPatientenIndexRoute
  '/praxis/patienten/$patientId': typeof AuthenticatedPraxisPatientenPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap': typeof SitemapRoute
  '/termin': typeof TerminRoute
  '/therapien': typeof TherapienRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/_authenticated/praxis': typeof AuthenticatedPraxisRouteRouteWithChildren
  '/_authenticated/mein-bereich': typeof AuthenticatedMeinBereichRoute
  '/_authenticated/praxis/anfragen': typeof AuthenticatedPraxisAnfragenRoute
  '/_authenticated/praxis/einstellungen': typeof AuthenticatedPraxisEinstellungenRoute
  '/_authenticated/praxis/heute': typeof AuthenticatedPraxisHeuteRoute
  '/_authenticated/praxis/kalender': typeof AuthenticatedPraxisKalenderRoute
  '/_authenticated/praxis/mahnungen': typeof AuthenticatedPraxisMahnungenRoute
  '/_authenticated/praxis/newsletter': typeof AuthenticatedPraxisNewsletterRoute
  '/_authenticated/praxis/rechnungen': typeof AuthenticatedPraxisRechnungenRoute
  '/_authenticated/praxis/suche': typeof AuthenticatedPraxisSucheRoute
  '/_authenticated/praxis/uebersicht': typeof AuthenticatedPraxisUebersichtRoute
  '/_authenticated/praxis/zahlungen': typeof AuthenticatedPraxisZahlungenRoute
  '/_authenticated/praxis/': typeof AuthenticatedPraxisIndexRoute
  '/_authenticated/praxis/patienten/': typeof AuthenticatedPraxisPatientenIndexRoute
  '/_authenticated/praxis/patienten/$patientId/': typeof AuthenticatedPraxisPatientenPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/sitemap'
    | '/termin'
    | '/therapien'
    | '/ueber-uns'
    | '/widerruf'
    | '/praxis'
    | '/mein-bereich'
    | '/praxis/anfragen'
    | '/praxis/einstellungen'
    | '/praxis/heute'
    | '/praxis/kalender'
    | '/praxis/mahnungen'
    | '/praxis/newsletter'
    | '/praxis/rechnungen'
    | '/praxis/suche'
    | '/praxis/uebersicht'
    | '/praxis/zahlungen'
    | '/praxis/'
    | '/praxis/patienten/'
    | '/praxis/patienten/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/sitemap'
    | '/termin'
    | '/therapien'
    | '/ueber-uns'
    | '/widerruf'
    | '/mein-bereich'
    | '/praxis/anfragen'
    | '/praxis/einstellungen'
    | '/praxis/heute'
    | '/praxis/kalender'
    | '/praxis/mahnungen'
    | '/praxis/newsletter'
    | '/praxis/rechnungen'
    | '/praxis/suche'
    | '/praxis/uebersicht'
    | '/praxis/zahlungen'
    | '/praxis'
    | '/praxis/patienten'
    | '/praxis/patienten/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/sitemap'
    | '/termin'
    | '/therapien'
    | '/ueber-uns'
    | '/widerruf'
    | '/_authenticated/praxis'
    | '/_authenticated/mein-bereich'
    | '/_authenticated/praxis/anfragen'
    | '/_authenticated/praxis/einstellungen'
    | '/_authenticated/praxis/heute'
    | '/_authenticated/praxis/kalender'
    | '/_authenticated/praxis/mahnungen'
    | '/_authenticated/praxis/newsletter'
    | '/_authenticated/praxis/rechnungen'
    | '/_authenticated/praxis/suche'
    | '/_authenticated/praxis/uebersicht'
    | '/_authenticated/praxis/zahlungen'
    | '/_authenticated/praxis/'
    | '/_authenticated/praxis/patienten/'
    | '/_authenticated/praxis/patienten/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  SitemapRoute: typeof SitemapRoute
  TerminRoute: typeof TerminRoute
  TherapienRoute: typeof TherapienRoute
  UeberUnsRoute: typeof UeberUnsRoute
  WiderrufRoute: typeof WiderrufRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termin': {
      id: '/termin'
      path: '/termin'
      fullPath: '/termin'
      preLoaderRoute: typeof TerminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapien': {
      id: '/therapien'
      path: '/therapien'
      fullPath: '/therapien'
      preLoaderRoute: typeof TherapienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mein-bereich': {
      id: '/_authenticated/mein-bereich'
      path: '/mein-bereich'
      fullPath: '/mein-bereich'
      preLoaderRoute: typeof AuthenticatedMeinBereichRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/praxis': {
      id: '/_authenticated/praxis'
      path: '/praxis'
      fullPath: '/praxis'
      preLoaderRoute: typeof AuthenticatedPraxisRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/praxis/': {
      id: '/_authenticated/praxis/'
      path: '/'
      fullPath: '/praxis/'
      preLoaderRoute: typeof AuthenticatedPraxisIndexRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/anfragen': {
      id: '/_authenticated/praxis/anfragen'
      path: '/anfragen'
      fullPath: '/praxis/anfragen'
      preLoaderRoute: typeof AuthenticatedPraxisAnfragenRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/einstellungen': {
      id: '/_authenticated/praxis/einstellungen'
      path: '/einstellungen'
      fullPath: '/praxis/einstellungen'
      preLoaderRoute: typeof AuthenticatedPraxisEinstellungenRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/heute': {
      id: '/_authenticated/praxis/heute'
      path: '/heute'
      fullPath: '/praxis/heute'
      preLoaderRoute: typeof AuthenticatedPraxisHeuteRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/kalender': {
      id: '/_authenticated/praxis/kalender'
      path: '/kalender'
      fullPath: '/praxis/kalender'
      preLoaderRoute: typeof AuthenticatedPraxisKalenderRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/mahnungen': {
      id: '/_authenticated/praxis/mahnungen'
      path: '/mahnungen'
      fullPath: '/praxis/mahnungen'
      preLoaderRoute: typeof AuthenticatedPraxisMahnungenRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/newsletter': {
      id: '/_authenticated/praxis/newsletter'
      path: '/newsletter'
      fullPath: '/praxis/newsletter'
      preLoaderRoute: typeof AuthenticatedPraxisNewsletterRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/rechnungen': {
      id: '/_authenticated/praxis/rechnungen'
      path: '/rechnungen'
      fullPath: '/praxis/rechnungen'
      preLoaderRoute: typeof AuthenticatedPraxisRechnungenRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/suche': {
      id: '/_authenticated/praxis/suche'
      path: '/suche'
      fullPath: '/praxis/suche'
      preLoaderRoute: typeof AuthenticatedPraxisSucheRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/uebersicht': {
      id: '/_authenticated/praxis/uebersicht'
      path: '/uebersicht'
      fullPath: '/praxis/uebersicht'
      preLoaderRoute: typeof AuthenticatedPraxisUebersichtRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/zahlungen': {
      id: '/_authenticated/praxis/zahlungen'
      path: '/zahlungen'
      fullPath: '/praxis/zahlungen'
      preLoaderRoute: typeof AuthenticatedPraxisZahlungenRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/patienten/': {
      id: '/_authenticated/praxis/patienten/'
      path: '/patienten'
      fullPath: '/praxis/patienten/'
      preLoaderRoute: typeof AuthenticatedPraxisPatientenIndexRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
    '/_authenticated/praxis/patienten/$patientId/': {
      id: '/_authenticated/praxis/patienten/$patientId/'
      path: '/patienten/$patientId'
      fullPath: '/praxis/patienten/$patientId/'
      preLoaderRoute: typeof AuthenticatedPraxisPatientenPatientIdIndexRouteImport
      parentRoute: typeof AuthenticatedPraxisRouteRoute
    }
  }
}

interface AuthenticatedPraxisRouteRouteChildren {
  AuthenticatedPraxisAnfragenRoute: typeof AuthenticatedPraxisAnfragenRoute
  AuthenticatedPraxisEinstellungenRoute: typeof AuthenticatedPraxisEinstellungenRoute
  AuthenticatedPraxisHeuteRoute: typeof AuthenticatedPraxisHeuteRoute
  AuthenticatedPraxisKalenderRoute: typeof AuthenticatedPraxisKalenderRoute
  AuthenticatedPraxisMahnungenRoute: typeof AuthenticatedPraxisMahnungenRoute
  AuthenticatedPraxisNewsletterRoute: typeof AuthenticatedPraxisNewsletterRoute
  AuthenticatedPraxisRechnungenRoute: typeof AuthenticatedPraxisRechnungenRoute
  AuthenticatedPraxisSucheRoute: typeof AuthenticatedPraxisSucheRoute
  AuthenticatedPraxisUebersichtRoute: typeof AuthenticatedPraxisUebersichtRoute
  AuthenticatedPraxisZahlungenRoute: typeof AuthenticatedPraxisZahlungenRoute
  AuthenticatedPraxisIndexRoute: typeof AuthenticatedPraxisIndexRoute
  AuthenticatedPraxisPatientenIndexRoute: typeof AuthenticatedPraxisPatientenIndexRoute
  AuthenticatedPraxisPatientenPatientIdIndexRoute: typeof AuthenticatedPraxisPatientenPatientIdIndexRoute
}

const AuthenticatedPraxisRouteRouteChildren: AuthenticatedPraxisRouteRouteChildren =
  {
    AuthenticatedPraxisAnfragenRoute: AuthenticatedPraxisAnfragenRoute,
    AuthenticatedPraxisEinstellungenRoute:
      AuthenticatedPraxisEinstellungenRoute,
    AuthenticatedPraxisHeuteRoute: AuthenticatedPraxisHeuteRoute,
    AuthenticatedPraxisKalenderRoute: AuthenticatedPraxisKalenderRoute,
    AuthenticatedPraxisMahnungenRoute: AuthenticatedPraxisMahnungenRoute,
    AuthenticatedPraxisNewsletterRoute: AuthenticatedPraxisNewsletterRoute,
    AuthenticatedPraxisRechnungenRoute: AuthenticatedPraxisRechnungenRoute,
    AuthenticatedPraxisSucheRoute: AuthenticatedPraxisSucheRoute,
    AuthenticatedPraxisUebersichtRoute: AuthenticatedPraxisUebersichtRoute,
    AuthenticatedPraxisZahlungenRoute: AuthenticatedPraxisZahlungenRoute,
    AuthenticatedPraxisIndexRoute: AuthenticatedPraxisIndexRoute,
    AuthenticatedPraxisPatientenIndexRoute:
      AuthenticatedPraxisPatientenIndexRoute,
    AuthenticatedPraxisPatientenPatientIdIndexRoute:
      AuthenticatedPraxisPatientenPatientIdIndexRoute,
  }

const AuthenticatedPraxisRouteRouteWithChildren =
  AuthenticatedPraxisRouteRoute._addFileChildren(
    AuthenticatedPraxisRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPraxisRouteRoute: typeof AuthenticatedPraxisRouteRouteWithChildren
  AuthenticatedMeinBereichRoute: typeof AuthenticatedMeinBereichRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPraxisRouteRoute: AuthenticatedPraxisRouteRouteWithChildren,
  AuthenticatedMeinBereichRoute: AuthenticatedMeinBereichRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  SitemapRoute: SitemapRoute,
  TerminRoute: TerminRoute,
  TherapienRoute: TherapienRoute,
  UeberUnsRoute: UeberUnsRoute,
  WiderrufRoute: WiderrufRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
