/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TerminRouteImport } from './routes/termin'
import { Route as TherapienRouteImport } from './routes/therapien'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as AuthenticatedPraxisRouteImport } from './routes/_authenticated/praxis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminRoute = TerminRouteImport.update({
  id: '/termin',
  path: '/termin',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapienRoute = TherapienRouteImport.update({
  id: '/therapien',
  path: '/therapien',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const WiderrufRoute = WiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPraxisRoute = AuthenticatedPraxisRouteImport.update({
  id: '/praxis',
  path: '/praxis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap': typeof SitemapRoute
  '/termin': typeof TerminRoute
  '/therapien': typeof TherapienRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/praxis': typeof AuthenticatedPraxisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap': typeof SitemapRoute
  '/termin': typeof TerminRoute
  '/therapien': typeof TherapienRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/praxis': typeof AuthenticatedPraxisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap': typeof SitemapRoute
  '/termin': typeof TerminRoute
  '/therapien': typeof TherapienRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/widerruf': typeof WiderrufRoute
  '/_authenticated/praxis': typeof AuthenticatedPraxisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/sitemap'
    | '/termin'
    | '/therapien'
    | '/ueber-uns'
    | '/widerruf'
    | '/praxis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/sitemap'
    | '/termin'
    | '/therapien'
    | '/ueber-uns'
    | '/widerruf'
    | '/praxis'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/sitemap'
    | '/termin'
    | '/therapien'
    | '/ueber-uns'
    | '/widerruf'
    | '/_authenticated/praxis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  SitemapRoute: typeof SitemapRoute
  TerminRoute: typeof TerminRoute
  TherapienRoute: typeof TherapienRoute
  UeberUnsRoute: typeof UeberUnsRoute
  WiderrufRoute: typeof WiderrufRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termin': {
      id: '/termin'
      path: '/termin'
      fullPath: '/termin'
      preLoaderRoute: typeof TerminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapien': {
      id: '/therapien'
      path: '/therapien'
      fullPath: '/therapien'
      preLoaderRoute: typeof TherapienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/praxis': {
      id: '/_authenticated/praxis'
      path: '/praxis'
      fullPath: '/praxis'
      preLoaderRoute: typeof AuthenticatedPraxisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPraxisRoute: typeof AuthenticatedPraxisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPraxisRoute: AuthenticatedPraxisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  SitemapRoute: SitemapRoute,
  TerminRoute: TerminRoute,
  TherapienRoute: TherapienRoute,
  UeberUnsRoute: UeberUnsRoute,
  WiderrufRoute: WiderrufRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
