// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tigizbcvceabjdbqelhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpZ2l6YmN2Y2VhYmpkYnFlbGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5MjA0MjIsImV4cCI6MjEwMTQ5NjQyMn0.QI3jtHGn0ly6VOOiRqC3VTR2UhPhsGXprD4kgo9JLBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});